apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend1
spec:
  containers:
  - image: quay.io/camo1995/node-web-app:1.1.1
    name: nodewebapp
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  
