apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    tier: frontend
  ports:
  - name: myport
    port: 8037
    protocol: TCP
    targetPort: 3040
  type: LoadBalancer
